apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aks-store-demo-prod
  namespace: default
spec:
  interval: 5m
  targetNamespace: aks-store-demo-prod
  chart:
    spec:
      chart: charts/aks-store-demo
      sourceRef:
        kind: GitRepository
        name: aks-store-demo-charts
        namespace: default
      interval: 1m
  values:
    # Production environment specific values
    replicaCount:
      order: 3
      product: 2
      store-front: 3
      store-admin: 2
      makeline: 2
      accounting: 2
      rabbitmq: 1
      mongodb: 1

    # Resource limits for production
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

    # Production specific configurations
    env: "production"

    # Production networking
    service:
      type: LoadBalancer
